/*
 * Copyright (c) 2014-2015, Linaro Ltd and Contributors. All rights reserved.
 * Copyright (c) 2014-2015, Hisilicon Ltd and Contributors. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * Neither the name of ARM nor the names of its contributors may be used
 * to endorse or promote products derived from this software without specific
 * prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include <hi6220.h>
#include <gpio.h>
#include <assert.h>
#include <debug.h>
#include <errno.h>
#include <mmio.h>
#include <stdint.h>
#include <string.h>

enum pinmux_init_mode {
	PMUX_M0 = 0,
	PMUX_M1,
	PMUX_M2,
	PMUX_M3,
	PMUX_M4,
	PMUX_M5,
	PMUX_M6,
	PMUX_M7
};

enum pinmux_pull_type {
	PMUX_NOPULL = 0,
	PMUX_PULL_UP,
	PMUX_PULL_DOWN,
};

enum pinmux_whether_gpio {
	FOR_GPIO = 0,
	NOT_FOR_GPIO,
};

enum pinmux_direction {
	PMUX_IN = 0,
	PMUX_OUT,
};

enum pinmux_output {
	PMUX_LOW = 0,
	PMUX_HIGH,
};

enum pinmux_slew_rate {
	SLEW_RATE = 0,
	SLEW_RATE_NOT,
	SLEW_RATE_NONSET,
};

enum pinmux_driver_current {
	PMUX_2MA_1   = 0x0,
	PMUX_4MA_1   = 0x1,
	PMUX_8MA_1   = 0x2,
	PMUX_10MA_1  = 0x3,
	PMUX_2MA_2   = 0x0,
	PMUX_4MA_2   = 0x1,
	PMUX_8MA_2   = 0x2,
	PMUX_10MA_2  = 0x3,
	PMUX_4MA_3   = 0x0,
	PMUX_8MA_3   = 0x1,
	PMUX_12MA_3  = 0x2,
	PMUX_16MA_3  = 0x3,
	PMUX_20MA_3  = 0x4,
	PMUX_24MA_3  = 0x5,
	PMUX_32MA_3  = 0x6,
	PMUX_40MA_3  = 0x7,
	PMUX_2MA_4   = 0x0,
	PMUX_4MA_4   = 0x2,
	PMUX_8MA_4   = 0x4,
	PMUX_10MA_4  = 0x6,
	DRIVER_NONSET   = 0xF,
};

struct pinmux_setting {
	unsigned int pin_name;
	unsigned int init_mode :3;
	unsigned int pull_type :2;
	unsigned int whether_gpio :1;
	unsigned int direction :2;
	unsigned int output :2;
	unsigned int gpioie :2;
	unsigned int current :4;
	unsigned int slew_rate :2;
};

struct gpio_io_info {
	unsigned int gpio_id;
	unsigned int iocg;
	unsigned int iomg;
};

struct gpio_io_info gpio_io_info[] = {
/* gpio           iocg reg      iomg reg    */
 { GPIO_0_0,      IOCG_004_ON,  NO_IOMG      },
 { GPIO_0_1,      IOCG_005_ON,  NO_IOMG      },
 { GPIO_0_2,      IOCG_006_ON,  NO_IOMG      },
 { GPIO_0_3,      IOCG_007_ON,  NO_IOMG      },
 { GPIO_0_4,      IOCG_008_ON,  NO_IOMG      },
 { GPIO_0_5,      IOCG_009_ON,  NO_IOMG      },
 { GPIO_0_6,      IOCG_010_ON,  NO_IOMG      },
 { GPIO_0_7,      IOCG_011_ON,  NO_IOMG      },
 { GPIO_1_0,      IOCG_012_ON,  NO_IOMG      },
 { GPIO_1_1,      IOCG_013_ON,  NO_IOMG      },
 { GPIO_1_2,      IOCG_014_ON,  NO_IOMG      },
 { GPIO_1_3,      IOCG_015_ON,  NO_IOMG      },
 { GPIO_1_4,      IOCG_016_ON,  NO_IOMG      },
 { GPIO_1_5,      IOCG_017_ON,  NO_IOMG      },
 { GPIO_1_6,      IOCG_018_ON,  NO_IOMG      },
 { GPIO_1_7,      IOCG_019_ON,  NO_IOMG      },
 { GPIO_2_0,      IOCG_020_ON,  NO_IOMG      },
 { GPIO_2_1,      IOCG_021_ON,  NO_IOMG      },
 { GPIO_2_2,      IOCG_022_ON,  NO_IOMG      },
 { GPIO_2_3,      IOCG_023_ON,  NO_IOMG      },
 { GPIO_2_4,      IOCG_024_ON,  NO_IOMG      },
 { GPIO_2_5,      IOCG_025_ON,  NO_IOMG      },
 { GPIO_2_6,      IOCG_026_ON,  NO_IOMG      },
 { GPIO_2_7,      IOCG_027_ON,  NO_IOMG      },
 { BOOT_SEL,      IOCG_000_OFF, IOMG_000_OFF },
 { GPIO_8_2,      IOCG_002_OFF, IOMG_002_OFF },
 { SD_CLK,        IOCG_003_OFF, IOMG_003_OFF },
 { SD_CMD,        IOCG_004_OFF, IOMG_004_OFF },
 { SD_DATA0,      IOCG_005_OFF, IOMG_005_OFF },
 { SD_DATA1,      IOCG_006_OFF, IOMG_006_OFF },
 { SD_DATA2,      IOCG_007_OFF, IOMG_007_OFF },
 { SD_DATA3,      IOCG_008_OFF, IOMG_008_OFF },
 { ISP_PWDN0,     IOCG_010_OFF, IOMG_009_OFF },
 { ISP_PWDN1,     IOCG_011_OFF, IOMG_010_OFF },
 { ISP_PWDN2,     IOCG_012_OFF, IOMG_011_OFF },
 { ISP_SHUTTER0,  IOCG_013_OFF, IOMG_012_OFF },
 { ISP_SHUTTER1,  IOCG_014_OFF, IOMG_013_OFF },
 { ISP_PWM,       IOCG_015_OFF, IOMG_014_OFF },
 { ISP_CCLK0,     IOCG_016_OFF, IOMG_015_OFF },
 { ISP_CCLK1,     IOCG_017_OFF, IOMG_016_OFF },
 { ISP_RESETB0,   IOCG_018_OFF, IOMG_017_OFF },
 { ISP_RESETB1,   IOCG_019_OFF, IOMG_018_OFF },
 { ISP_STROBE0,   IOCG_020_OFF, IOMG_019_OFF },
 { ISP_STROBE1,   IOCG_021_OFF, IOMG_020_OFF },
 { ISP_SDA0,      IOCG_022_OFF, IOMG_021_OFF },
 { ISP_SCL0,      IOCG_023_OFF, IOMG_022_OFF },
 { ISP_SDA1,      IOCG_024_OFF, IOMG_023_OFF },
 { ISP_SCL1,      IOCG_025_OFF, IOMG_024_OFF },
 { GPIO_11_2,     IOCG_026_OFF, IOMG_025_OFF },
 { DMIC_CLK,      IOCG_029_OFF, IOMG_028_OFF },
 { CODEC_SYNC,    IOCG_030_OFF, IOMG_029_OFF },
 { CODEC_DATAIN,  IOCG_031_OFF, IOMG_030_OFF },
 { CODEC_DATAOUT, IOCG_032_OFF, IOMG_031_OFF },
 { FM_XCLK,       IOCG_033_OFF, IOMG_032_OFF },
 { FM_XFS,        IOCG_034_OFF, IOMG_033_OFF },
 { FM_DI,         IOCG_035_OFF, IOMG_034_OFF },
 { FM_DO,         IOCG_036_OFF, IOMG_035_OFF },
 { USIM1_CLK,     IOCG_044_OFF, IOMG_043_OFF },
 { USIM1_DATA,    IOCG_045_OFF, IOMG_044_OFF },
 { USIM1_RST,     IOCG_046_OFF, IOMG_045_OFF },
 { PWM_IN,        IOCG_047_OFF, IOMG_046_OFF },
 { BL_PWM,        IOCG_048_OFF, IOMG_047_OFF },
 { UART0_RXD,     IOCG_049_OFF, IOMG_048_OFF },
 { UART0_TXD,     IOCG_050_OFF, IOMG_049_OFF },
 { UART1_CTS_N,   IOCG_051_OFF, IOMG_050_OFF },
 { UART1_RTS_N,   IOCG_052_OFF, IOMG_051_OFF },
 { UART1_RXD,     IOCG_053_OFF, IOMG_052_OFF },
 { UART1_TXD,     IOCG_054_OFF, IOMG_053_OFF },
 { UART2_CTS_N,   IOCG_055_OFF, IOMG_054_OFF },
 { UART2_RTS_N,   IOCG_056_OFF, IOMG_055_OFF },
 { UART2_RXD,     IOCG_057_OFF, IOMG_056_OFF },
 { UART2_TXD,     IOCG_058_OFF, IOMG_057_OFF },
 { I2C0_SCL,      IOCG_059_OFF, IOMG_058_OFF },
 { I2C0_SDA,      IOCG_060_OFF, IOMG_059_OFF },
 { I2C1_SCL,      IOCG_061_OFF, IOMG_060_OFF },
 { I2C1_SDA,      IOCG_062_OFF, IOMG_061_OFF },
 { I2C2_SCL,      IOCG_063_OFF, IOMG_062_OFF },
 { I2C2_SDA,      IOCG_064_OFF, IOMG_063_OFF },
 { SDIO_CLK,      IOCG_077_OFF, IOMG_074_OFF },
 { SDIO_CMD,      IOCG_078_OFF, IOMG_075_OFF },
 { SDIO_DATA0,    IOCG_079_OFF, IOMG_076_OFF },
 { SDIO_DATA1,    IOCG_080_OFF, IOMG_077_OFF },
 { SDIO_DATA2,    IOCG_081_OFF, IOMG_078_OFF },
 { SDIO_DATA3,    IOCG_082_OFF, IOMG_079_OFF },
 { GPIO_3_0,      IOCG_084_OFF, IOMG_080_OFF },
 { GPIO_3_1,      IOCG_085_OFF, IOMG_081_OFF },
 { GPIO_3_2,      IOCG_086_OFF, IOMG_082_OFF },
 { GPIO_3_3,      IOCG_087_OFF, IOMG_083_OFF },
 { AUX_SSI0,      IOCG_088_OFF, IOMG_084_OFF },
 { GPIO_3_5,      IOCG_089_OFF, IOMG_085_OFF },
 { GPIO_3_6,      IOCG_090_OFF, IOMG_086_OFF },
 { GPIO_3_7,      IOCG_091_OFF, IOMG_087_OFF },
 { GPIO_4_0,      IOCG_092_OFF, IOMG_088_OFF },
 { GPIO_4_1,      IOCG_093_OFF, IOMG_089_OFF },
 { GPIO_4_2,      IOCG_094_OFF, IOMG_090_OFF },
 { GPIO_4_3,      IOCG_095_OFF, IOMG_091_OFF },
 { GPIO_4_4,      IOCG_096_OFF, IOMG_092_OFF },
 { GPIO_4_5,      IOCG_097_OFF, IOMG_093_OFF },
 { GPIO_4_6,      IOCG_098_OFF, IOMG_094_OFF },
 { GPIO_4_7,      IOCG_099_OFF, IOMG_095_OFF },
 { GPIO_5_0,      IOCG_100_OFF, IOMG_096_OFF },
 { GPIO_5_1,      IOCG_101_OFF, IOMG_097_OFF },
 { GPIO_5_2,      IOCG_102_OFF, IOMG_098_OFF },
 { GPIO_5_3,      IOCG_103_OFF, IOMG_099_OFF },
 { GPIO_5_4,      IOCG_104_OFF, IOMG_100_OFF },
 { GPIO_5_5,      IOCG_105_OFF, IOMG_101_OFF },
 { GPIO_5_6,      IOCG_106_OFF, IOMG_102_OFF },
 { GPIO_5_7,      IOCG_107_OFF, IOMG_103_OFF },
 { GPIO_6_0,      IOCG_108_OFF, IOMG_104_OFF },
 { GPIO_6_1,      IOCG_109_OFF, IOMG_105_OFF },
 { GPIO_6_2,      IOCG_110_OFF, IOMG_106_OFF },
 { GPIO_6_3,      IOCG_111_OFF, IOMG_107_OFF },
 { GPIO_6_4,      IOCG_112_OFF, IOMG_108_OFF },
 { GPIO_6_5,      IOCG_113_OFF, IOMG_109_OFF },
 { GPIO_6_6,      IOCG_114_OFF, IOMG_110_OFF },
 { GPIO_6_7,      IOCG_115_OFF, IOMG_111_OFF },
 { GPIO_7_0,      IOCG_116_OFF, IOMG_112_OFF },
 { GPIO_7_1,      IOCG_117_OFF, IOMG_113_OFF },
 { GPIO_7_2,      IOCG_118_OFF, IOMG_114_OFF },
 { GPIO_7_3,      IOCG_119_OFF, IOMG_115_OFF },
 { GPIO_7_4,      IOCG_120_OFF, IOMG_116_OFF },
 { GPIO_7_5,      IOCG_121_OFF, IOMG_117_OFF },
 { GPIO_7_6,      IOCG_122_OFF, IOMG_118_OFF },
 { GPIO_7_7,      IOCG_123_OFF, IOMG_119_OFF },
 { GPIO_8_0,      IOCG_124_OFF, IOMG_120_OFF },
 { GPIO_8_1,      IOCG_125_OFF, IOMG_121_OFF },
 { TCXO0_AFC,     IOCG_126_OFF, IOMG_122_OFF },
 { RF_SSI0,       IOCG_127_OFF, IOMG_123_OFF },
 { RF_TCVR_ON0,   IOCG_128_OFF, IOMG_124_OFF },
 { RF_MIPI_CLK0,  IOCG_129_OFF, IOMG_125_OFF },
 { RF_MIPI_DATA0, IOCG_130_OFF, IOMG_126_OFF },
 { RF_GPIO_0,     IOCG_131_OFF, IOMG_127_OFF },
 { RF_GPIO_1,     IOCG_132_OFF, IOMG_128_OFF },
 { RF_GPIO_2,     IOCG_133_OFF, IOMG_129_OFF },
 { RF_GPIO_3,     IOCG_134_OFF, IOMG_130_OFF },
 { RF_GPIO_4,     IOCG_135_OFF, IOMG_131_OFF },
 { RF_GPIO_5,     IOCG_136_OFF, IOMG_132_OFF },
 { RF_GPIO_6,     IOCG_137_OFF, IOMG_133_OFF },
 { RF_GPIO_7,     IOCG_138_OFF, IOMG_134_OFF },
 { RF_GPIO_8,     IOCG_139_OFF, IOMG_135_OFF },
 { RF_GPIO_9,     IOCG_140_OFF, IOMG_136_OFF },
 { RF_GPIO_10,    IOCG_141_OFF, IOMG_137_OFF },
 { RF_GPIO_11,    IOCG_142_OFF, IOMG_138_OFF },
 { RF_GPIO_12,    IOCG_143_OFF, IOMG_139_OFF },
 { RF_GPIO_13,    IOCG_144_OFF, IOMG_140_OFF },
 { RF_GPIO_14,    IOCG_145_OFF, IOMG_141_OFF },
 { RF_GPIO_15,    IOCG_146_OFF, IOMG_142_OFF },
 { RF_GPIO_16,    IOCG_147_OFF, IOMG_143_OFF },
 { RF_GPIO_17,    IOCG_148_OFF, IOMG_144_OFF },
 { RF_GPIO_18,    IOCG_149_OFF, IOMG_145_OFF },
 { RF_GPIO_19,    IOCG_150_OFF, IOMG_146_OFF },
 { RF_GPIO_20,    IOCG_151_OFF, IOMG_147_OFF },
 { RF_GPIO_21,    IOCG_152_OFF, IOMG_148_OFF },
 { RF_GPIO_22,    IOCG_153_OFF, IOMG_149_OFF },
 { RF_GPIO_23,    IOCG_154_OFF, IOMG_150_OFF },
 { RF_GPIO_24,    IOCG_155_OFF, IOMG_151_OFF },
 { RF_GPIO_25,    IOCG_156_OFF, IOMG_152_OFF },
 { RF_GPIO_26,    IOCG_157_OFF, IOMG_153_OFF },
 { RF_GPIO_27,    IOCG_158_OFF, IOMG_154_OFF },
 { RF_GPIO_28,    IOCG_159_OFF, IOMG_155_OFF },
 { RF_GPIO_29,    IOCG_160_OFF, IOMG_156_OFF },
 { RF_GPIO_30,    IOCG_161_OFF, IOMG_157_OFF },
 { APT_PDM0,      IOCG_162_OFF, IOMG_158_OFF },
 { END_SYMBOL,    END_SYMBOL,   END_SYMBOL   },
};

struct pinmux_setting hi6220_pinmux_init_table[] = {
/* gpio_name    init_mode       pull_type       for_gpio        direction       out_value       intr_core       current         slew_rate     */
 { GPIO_0_0,	PMUX_M0,	PMUX_NOPULL,	FOR_GPIO,	PMUX_OUT,	PMUX_HIGH,	INTR_CORE_NULL,	PMUX_2MA_1,	SLEW_RATE_NOT },
 { GPIO_0_1,	PMUX_M0, 	PMUX_NOPULL,	FOR_GPIO,	PMUX_OUT,	PMUX_LOW,	INTR_CORE_AP,	PMUX_2MA_1,	SLEW_RATE_NOT },
 { GPIO_0_2,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_AP,	PMUX_2MA_1,	SLEW_RATE_NOT },
 { GPIO_0_3,	PMUX_M0,	PMUX_NOPULL,	FOR_GPIO,	PMUX_OUT,	PMUX_LOW,	INTR_CORE_NULL,	PMUX_2MA_1,	SLEW_RATE_NOT },
 { GPIO_0_4,	PMUX_M0,	PMUX_NOPULL,	FOR_GPIO,	PMUX_OUT,	PMUX_LOW,	INTR_CORE_AP,	PMUX_2MA_1,	SLEW_RATE_NOT },
 { GPIO_0_5,	PMUX_M0,	PMUX_NOPULL,	FOR_GPIO,	PMUX_OUT,	PMUX_LOW,	INTR_CORE_NULL,	PMUX_2MA_1,	SLEW_RATE_NOT },
 { GPIO_0_6,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_AP,	PMUX_2MA_1,	SLEW_RATE_NOT },
 { GPIO_0_7,	PMUX_M0,	PMUX_NOPULL,	FOR_GPIO,	PMUX_OUT,	PMUX_LOW,	INTR_CORE_AP,	PMUX_2MA_1,	SLEW_RATE_NOT },
 { GPIO_1_0,	PMUX_M0,	PMUX_NOPULL,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_AP,	PMUX_2MA_1,	SLEW_RATE_NOT },
 { GPIO_1_1,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_1,	SLEW_RATE_NOT },
 { GPIO_1_2,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_AP,	PMUX_2MA_1,	SLEW_RATE_NOT },
 { GPIO_1_3,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_AP,	PMUX_2MA_1,	SLEW_RATE_NOT },
 { GPIO_1_4,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_AP,	PMUX_2MA_1,	SLEW_RATE_NOT },
 { GPIO_1_5,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_1,	SLEW_RATE_NOT },
 { GPIO_1_6,	PMUX_M0,	PMUX_PULL_UP,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_AP,	PMUX_2MA_1,	SLEW_RATE_NOT },
 { GPIO_1_7,	PMUX_M0,	PMUX_NOPULL,	FOR_GPIO,	PMUX_OUT,	PMUX_LOW,	INTR_CORE_AP,	PMUX_2MA_1,	SLEW_RATE_NOT },
 { GPIO_2_0,	PMUX_M0,	PMUX_NOPULL,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_AP,	PMUX_2MA_1,	SLEW_RATE_NOT },
 { GPIO_2_1,	PMUX_M0,	PMUX_NOPULL,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_AP,	PMUX_2MA_1,	SLEW_RATE_NOT },
 { GPIO_2_2,	PMUX_M0,	PMUX_NOPULL,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_AP,	PMUX_2MA_1,	SLEW_RATE_NOT },
 { GPIO_2_3,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_AP,	PMUX_2MA_1,	SLEW_RATE_NOT },
 { GPIO_2_4,	PMUX_M0,	PMUX_NOPULL,	FOR_GPIO,	PMUX_OUT,	PMUX_LOW,	INTR_CORE_NULL,	PMUX_2MA_1,	SLEW_RATE_NOT },
 { GPIO_2_5,	PMUX_M0,	PMUX_PULL_UP,	FOR_GPIO,	PMUX_IN,	PMUX_LOW,	INTR_CORE_NULL,	PMUX_2MA_1,	SLEW_RATE_NOT },
 { GPIO_2_6,	PMUX_M0,	PMUX_PULL_UP,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_1,	SLEW_RATE_NOT },
 { GPIO_2_7,	PMUX_M0,	PMUX_PULL_UP,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_MODEM,PMUX_2MA_1,	SLEW_RATE_NOT },
 { BOOT_SEL,	PMUX_M0,	PMUX_PULL_UP,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_8_2,	PMUX_M1,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { SD_CLK,	PMUX_M1,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_4MA_3,	SLEW_RATE_NOT },
 { SD_CMD,	PMUX_M1,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_4MA_3,	SLEW_RATE_NOT },
 { SD_DATA0,	PMUX_M1,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_4MA_3,	SLEW_RATE_NOT },
 { SD_DATA1,	PMUX_M1,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_4MA_3,	SLEW_RATE_NOT },
 { SD_DATA2,	PMUX_M1,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_4MA_3,	SLEW_RATE_NOT },
 { SD_DATA3,	PMUX_M1,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_4MA_3,	SLEW_RATE_NOT },
 { ISP_PWDN0,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { ISP_PWDN1,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { ISP_PWDN2,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { ISP_SHUTTER0,PMUX_M1,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { ISP_SHUTTER1,PMUX_M1,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { ISP_PWM,	PMUX_M1,	PMUX_NOPULL,	FOR_GPIO,	PMUX_OUT,	PMUX_LOW,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { ISP_CCLK0,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { ISP_CCLK1,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { ISP_RESETB0,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { ISP_RESETB1,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { ISP_STROBE0,	PMUX_M1,	PMUX_NOPULL,	FOR_GPIO,	PMUX_OUT,	PMUX_LOW,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { ISP_STROBE1,	PMUX_M1,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { ISP_SDA0,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { ISP_SCL0,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { ISP_SDA1,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { ISP_SCL1,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_11_2,	PMUX_M1,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { DMIC_CLK,	PMUX_M1,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { CODEC_SYNC,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { CODEC_DATAIN,PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { CODEC_DATAOUT,PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { FM_XCLK,	PMUX_M1,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { FM_XFS,	PMUX_M1,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { FM_DI,	PMUX_M1,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { FM_DO,	PMUX_M1,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { USIM1_CLK,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	DRIVER_NONSET,	SLEW_RATE_NOT },
 { USIM1_DATA,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	DRIVER_NONSET,	SLEW_RATE_NOT },
 { USIM1_RST,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	DRIVER_NONSET,	SLEW_RATE_NOT },
 { PWM_IN,	PMUX_M1,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { BL_PWM,	PMUX_M1,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { UART0_RXD,	PMUX_M0,	PMUX_PULL_UP,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { UART0_TXD,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_4MA_2,	SLEW_RATE_NOT },
 { UART1_CTS_N,	PMUX_M1,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { UART1_RTS_N,	PMUX_M1,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { UART1_RXD,	PMUX_M1,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { UART1_TXD,	PMUX_M1,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { UART2_CTS_N,	PMUX_M1,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { UART2_RTS_N,	PMUX_M1,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { UART2_RXD,	PMUX_M1,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { UART2_TXD,	PMUX_M1,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { I2C0_SCL,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { I2C0_SDA,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { I2C1_SCL,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { I2C1_SDA,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { I2C2_SCL,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { I2C2_SDA,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { SDIO_CLK,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { SDIO_CMD,	PMUX_M0,	PMUX_PULL_UP,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { SDIO_DATA0,	PMUX_M0,	PMUX_PULL_UP,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { SDIO_DATA1,	PMUX_M0,	PMUX_PULL_UP,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { SDIO_DATA2,	PMUX_M0,	PMUX_PULL_UP,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { SDIO_DATA3,	PMUX_M0,	PMUX_PULL_UP,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_3_0,	PMUX_M0,	PMUX_NOPULL,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_AP,	PMUX_2MA_1,	SLEW_RATE_NOT },
 { GPIO_3_1,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_3_2,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_3_3,	PMUX_M0,	PMUX_NOPULL,	FOR_GPIO,	PMUX_OUT,	PMUX_LOW,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { AUX_SSI0,	PMUX_M1,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_3_5,	PMUX_M0,	PMUX_NOPULL,	FOR_GPIO,	PMUX_OUT,	PMUX_LOW,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_3_6,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_3_7,	PMUX_M0,	PMUX_NOPULL,	FOR_GPIO,	PMUX_OUT,	PMUX_LOW,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_4_0,	PMUX_M0,	PMUX_NOPULL,	FOR_GPIO,	PMUX_OUT,	PMUX_LOW,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_4_1,	PMUX_M0,	PMUX_NOPULL,	FOR_GPIO,	PMUX_OUT,	PMUX_LOW,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_4_2,	PMUX_M0,	PMUX_NOPULL,	FOR_GPIO,	PMUX_OUT,	PMUX_LOW,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_4_3,	PMUX_M0,	PMUX_NOPULL,	FOR_GPIO,	PMUX_OUT,	PMUX_LOW,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_4_4,	PMUX_M0,	PMUX_NOPULL,	FOR_GPIO,	PMUX_OUT,	PMUX_LOW,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_4_5,	PMUX_M1,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_4_6,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_4_7,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_5_0,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_5_1,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_5_2,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_5_3,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_5_4,	PMUX_M3,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_5_5,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_5_6,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_5_7,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_6_0,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_6_1,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_6_2,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_6_3,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_6_4,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_6_5,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_6_6,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_6_7,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_7_0,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_7_1,	PMUX_M0,	PMUX_PULL_UP,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_AP,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_7_2,	PMUX_M1,	PMUX_PULL_UP,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_7_3,	PMUX_M1,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_7_4,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_7_5,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_7_6,	PMUX_M1,	PMUX_PULL_UP,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_7_7,	PMUX_M1,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_8_0,	PMUX_M0,	PMUX_NOPULL,	FOR_GPIO,	PMUX_OUT,	PMUX_LOW,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { GPIO_8_1,	PMUX_M0,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { TCXO0_AFC,	PMUX_M1,	PMUX_PULL_DOWN,	FOR_GPIO,	PMUX_IN,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_MIPI_DATA0,PMUX_M0,	PMUX_PULL_DOWN,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_0,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_1,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_2,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_3,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_4,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_5,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_6,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_7,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_8,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_9,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_10,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_11,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_12,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_13,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_14,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_15,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_16,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_17,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_18,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_19,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_20,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_21,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_22,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_23,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_24,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_25,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_26,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_27,	PMUX_M2,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_28,	PMUX_M2,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_29,	PMUX_M2,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { RF_GPIO_30,	PMUX_M2,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { APT_PDM0,	PMUX_M0,	PMUX_NOPULL,	NOT_FOR_GPIO,	PMUX_NONSET,	PMUX_NONSET,	INTR_CORE_NULL,	PMUX_2MA_2,	SLEW_RATE_NOT },
 { END_SYMBOL,	END_SYMBOL,	END_SYMBOL,	END_SYMBOL,	END_SYMBOL,	END_SYMBOL, 	END_SYMBOL,	END_SYMBOL,	END_SYMBOL    },
};

static struct gpio_io_info *find_gpio_io_info(unsigned int gpio_id)
{
	struct gpio_io_info *info = NULL;
	int index = 0;

	info = (struct gpio_io_info *)(&(gpio_io_info[index]));

	while (info->gpio_id != END_SYMBOL) {

		if (gpio_id == info->gpio_id) {
			VERBOSE("[PINMUX]: find iocg/iomg for gpio %d\n",
				gpio_id);
			return info;
		}

		index++;
		info = &(gpio_io_info[index]);
	}

	return NULL;
}

void hikey_pinmux_init(void)
{
	unsigned int pin_name;
	unsigned int init_mode;
	unsigned int pull_type;
	unsigned int direction;
	unsigned int output;
	unsigned int gpioie;
	unsigned int iocg, iomg;
	unsigned int gpio_id;

	struct gpio_io_info *info = NULL;
	struct pinmux_setting *entry;

	gpio_register_device(GPIO0_BASE);
	gpio_register_device(GPIO1_BASE);
	gpio_register_device(GPIO2_BASE);
	gpio_register_device(GPIO3_BASE);
	gpio_register_device(GPIO4_BASE);
	gpio_register_device(GPIO5_BASE);
	gpio_register_device(GPIO6_BASE);
	gpio_register_device(GPIO7_BASE);
	gpio_register_device(GPIO8_BASE);
	gpio_register_device(GPIO9_BASE);
	gpio_register_device(GPIO10_BASE);
	gpio_register_device(GPIO11_BASE);
	gpio_register_device(GPIO12_BASE);
	gpio_register_device(GPIO13_BASE);
	gpio_register_device(GPIO14_BASE);
	gpio_register_device(GPIO15_BASE);
	gpio_register_device(GPIO16_BASE);
	gpio_register_device(GPIO17_BASE);
	gpio_register_device(GPIO18_BASE);
	gpio_register_device(GPIO19_BASE);

	for (entry = hi6220_pinmux_init_table;
	     entry->pin_name != END_SYMBOL; entry++) {

		pin_name  = entry->pin_name;
		init_mode = entry->init_mode;
		pull_type = entry->pull_type;
		direction = entry->direction;
		output    = entry->output;
		gpioie    = entry->gpioie;

		info = find_gpio_io_info(pin_name);
		if (!info)
			continue;

		iocg    = info->iocg;
		iomg    = info->iomg;
		gpio_id = info->gpio_id;

		VERBOSE("[GPIOMUX] pin_name:  %d\n", entry->pin_name);
		VERBOSE("[GPIOMUX] init_mode: %d\n", entry->init_mode);
		VERBOSE("[GPIOMUX] pull_type: %d\n", entry->pull_type);
		VERBOSE("[GPIOMUX] direction: %d\n", entry->direction);
		VERBOSE("[GPIOMUX] current:   %d\n", entry->current);
		VERBOSE("[GPIOMUX] gpioie:    %d\n", entry->gpioie);
		VERBOSE("[GPIOMUX] slew_rate: %d\n", entry->slew_rate);
		VERBOSE("[GPIOMUX] gpio_id:   %d\n", gpio_id);

		if (gpio_id >= PINMUX_SPECIFIC_USE) {
			if (iomg != NO_IOMG) {
				init_mode |= (mmio_read_32(iomg) & GPIO_MODE_MASK);
				mmio_write_32(iomg, init_mode);
			}

			continue;
		}

		if (pull_type != PMUX_NONSET) {
			pull_type |= (mmio_read_32(iocg) & GPIO_PULL_MASK);
			mmio_write_32(iocg, pull_type);
		}

		/* set gpio's intr for A/C/M core */
		if (gpioie < INTR_CORE_NULL)
			gpio_set_intr_input(gpio_id, gpioie);

		if (direction == PMUX_IN)
			gpio_direction_input(gpio_id);
		else if (direction == PMUX_OUT) {
			gpio_direction_output(gpio_id);
			gpio_set_value(gpio_id, output);
		}

		if (iomg != NO_IOMG) {
			init_mode |= (mmio_read_32(iomg) & GPIO_MODE_MASK);
			mmio_write_32(iomg, init_mode);
		}
	}

	return;
}
